version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3307:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - bridge
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:3306"]
        interval: 30s
        timeout: 10s
        retries: 5      

  metrics_calculator_service:
    build: ./stacking_layers_metrics_calculation/
    environment:
      - APPLICATION_BASIC_LOG_LEVEL=DEBUG
      - CHECK_APP_HEATH_TIME_SCHEDULER_SECONDS=6
      - DATABASE_HOST_URL=db
      - DATABASE_USER=user
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=db
    ports: 
      - '8000:8000'
    depends_on:
      - db
    links: 
      - db
    networks:
      - bridge
    restart: on-failure

  machine_service:
    build: ./stacking_layers_machine/
    environment:
      - APPLICATION_BASIC_LOG_LEVEL=DEBUG
      - STACKING_LAYERS_METRICS_SERVICE_URL=http://metrics_calculator_service:8000/machines_metrics/input/save
      - MACHINE_DATA_TIME_SCHEDULER_SECONDS=5
      - DATABASE_HOST_URL=db
      - DATABASE_USER=user
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=db
    depends_on:
      - db
    links: 
      - db
    networks:
      - bridge
    restart: on-failure

# Names our volume
volumes:
  my-db:

networks:
    bridge:
        driver: bridge    